'use server';

/**
 * @fileOverview This file defines a Genkit flow for providing smart search suggestions based on semantic similarity.
 *
 * The flow takes a user's search query as input and returns a list of suggested search terms.
 * The suggestions are generated by comparing the input query to a corpus of known item descriptions.
 *
 * - `getSmartSearchSuggestions` - A function that handles the smart search suggestions process.
 * - `SmartSearchSuggestionsInput` - The input type for the `getSmartSearchSuggestions` function.
 * - `SmartSearchSuggestionsOutput` - The return type for the `getSmartSearchSuggestions` function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SmartSearchSuggestionsInputSchema = z.object({
  query: z.string().describe('The user\u2019s search query.'),
});
export type SmartSearchSuggestionsInput = z.infer<
  typeof SmartSearchSuggestionsInputSchema
>;

const SmartSearchSuggestionsOutputSchema = z.object({
  suggestions: z
    .array(z.string())
    .describe('A list of suggested search terms.'),
});
export type SmartSearchSuggestionsOutput = z.infer<
  typeof SmartSearchSuggestionsOutputSchema
>;

export async function getSmartSearchSuggestions(
  input: SmartSearchSuggestionsInput
): Promise<SmartSearchSuggestionsOutput> {
  return smartSearchSuggestionsFlow(input);
}

const smartSearchSuggestionsPrompt = ai.definePrompt({
  name: 'smartSearchSuggestionsPrompt',
  input: {schema: SmartSearchSuggestionsInputSchema},
  output: {schema: SmartSearchSuggestionsOutputSchema},
  prompt: `You are an AI assistant that provides smart search suggestions based on semantic similarity.

  The user has entered the following search query: {{{query}}}

  Generate a list of suggested search terms that are semantically similar to the query.
  The suggestions should help the user find relevant items even if they don't know the exact keywords.

  Suggestions:`,
});

const smartSearchSuggestionsFlow = ai.defineFlow(
  {
    name: 'smartSearchSuggestionsFlow',
    inputSchema: SmartSearchSuggestionsInputSchema,
    outputSchema: SmartSearchSuggestionsOutputSchema,
  },
  async input => {
    const {output} = await smartSearchSuggestionsPrompt(input);
    return output!;
  }
);
